const types = {
  LOGIN_START: 'LOGIN_START',
  LOGIN_FINISHED: 'LOGIN_FINISHED',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT_START: 'LOGOUT_START',
  LOGOUT_FINISHED: 'LOGOUT_FINISHED',
  LOGOUT_ERROR: 'LOGOUT_ERROR',
  FETCH_DATES_START: 'FETCH_DATES_START',
  FETCH_DATES_FINISHED: 'FETCH_DATES_FINISHED',
  FETCH_DATES_ERROR: 'FETCH_DATES_ERROR',
  ADD_DATES_START: 'ADD_DATES_START',
  ADD_DATES_FINISHED: 'ADD_DATES_FINISHED',
  ADD_DATES_ERROR: 'ADD_DATES_ERROR',
};

export default types;
